# Generated by Django 5.0.6 on 2024-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptolist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
