# Generated by Django 5.0.6 on 2024-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cryptolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptolist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
